### ISSUE TITLE
Formulario de contacto

### ISSUE THREAD

**Issue by FedericoBordini** [Ignaciobressa/Proyecto_final#2]
La imagen de contacto se ve a la izquierda y es más incómodo para ver, además de que está desalineado. Falta espacio entre los campos, el campo de apellido está mal ubicado. 
![imagen de contacto](https://user-images.githubusercontent.com/21134315/27460824-a8a537bc-578c-11e7-84bc-50479de2e4f6.png)

**Comment by relezcano** [comment]
Solucionado!
